spring.application.name=UserService
spring.docker.compose.enabled=false
server.port=${SERVER_PORT:8081}

# JWT Configuration
jwt.expirationMs=300000
jwt.refreshExpirationMs=604800000

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

# Eureka Client Configuration
eureka.client.enabled=${EUREKA_CLIENT_ENABLED}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=${EUREKA_REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${EUREKA_FETCH_REGISTRY}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
eureka.instance.status-page-url=http://${eureka.instance.hostname}:${server.port}/swagger-ui/index.html
eureka.instance.health-check-url=http://${eureka.instance.hostname}:${server.port}/actuator/health

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
