spring.application.name=UserService
spring.docker.compose.enabled=false

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expirationMs=86400000
jwt.refreshExpirationMs=604800000

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
