spring.application.name=NotificationService

# Server
server.port=${SERVER_PORT}

# Docker Compose
spring.docker.compose.enabled=false

# MariaDB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.enabled=${EUREKA_CLIENT_ENABLED}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=${EUREKA_REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${EUREKA_FETCH_REGISTRY}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}

# Mail
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# App
app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}
