spring.application.name=CartService

server.port=${SERVER_PORT:8084}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/cart_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=${EUREKA_REGISTER_WITH_EUREKA:true}
eureka.client.fetch-registry=${EUREKA_FETCH_REGISTRY:true}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:cartservice}
eureka.instance.instance-id=CartService:${EUREKA_INSTANCE_HOSTNAME:cartservice}:${SERVER_PORT:8084}
eureka.instance.status-page-url=http://${EUREKA_INSTANCE_HOSTNAME:cartservice}:${SERVER_PORT:8084}/swagger-ui/index.html
eureka.instance.health-check-url=http://${EUREKA_INSTANCE_HOSTNAME:cartservice}:${SERVER_PORT:8084}/actuator/health

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
